# Generated by Django 3.0.8 on 2020-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200714_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college',
            field=models.CharField(max_length=300),
        ),
    ]
