# Generated by Django 3.0.8 on 2020-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200720_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professors',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='professors',
            name='professor_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='professors',
            name='college',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='professors',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.CharField(max_length=5),
        ),
    ]
