# Generated by Django 3.0.8 on 2020-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200723_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
