# Generated by Django 3.0.8 on 2020-07-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200724_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('College', 'College'), ('Professor', 'Professor')], max_length=100),
        ),
    ]
