# Generated by Django 3.0.8 on 2020-08-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='attendance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
