# Generated by Django 3.0.8 on 2020-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_students_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='today_attendance',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
