# Generated by Django 3.0.8 on 2020-08-02 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20200802_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2020, 8, 2)),
        ),
    ]
