# Generated by Django 3.0.8 on 2020-08-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20200802_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
