# Generated by Django 3.0.8 on 2020-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20200802_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
