# Generated by Django 3.0.8 on 2020-08-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_customuser_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='abc',
        ),
    ]
