# Generated by Django 3.0.8 on 2020-08-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_customuser_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='college',
        ),
        migrations.AddField(
            model_name='professors',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
