# Generated by Django 3.0.8 on 2020-08-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20200814_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='total_attendance',
            field=models.IntegerField(default=0),
        ),
    ]
